# Generated by Django 5.1.1 on 2024-09-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiquery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIQueryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_fields', models.TextField()),
                ('base_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
