# Generated by Django 5.0.7 on 2024-07-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embed_dim',
            field=models.IntegerField(default=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='embed_type',
            field=models.TextField(default='bga-large'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='table_name',
            field=models.TextField(default='data_documents'),
            preserve_default=False,
        ),
    ]
